### ISSUE TITLE
'Rekognition' object has no attribute 'detect_protective_equipment'

### ISSUE THREAD

**Issue by kaiw1ng** [aws-samples/amazon-rekognition-ppe#43]
boto3 appears to be unaware of 'detect_protective_equipment' 
boto3 - do i have to update anything?

**Comment by matteofigus** [comment]
Thanks for opening an issue. This error happens if you are using an old version of boto3. Please upgrade the version of boto3 to solve the issue.

If you are using Lambda, you need to package it together with the library.

I hope it helps.
