### ISSUE TITLE
How can I run/test this PPE Application locally

### ISSUE THREAD

**Issue by RamGitHub83** [aws-samples/amazon-rekognition-ppe#44]
Hi Team,

Thanks for sharing sample application.

As per guidelines, I had deployed in AWS through Cloud Formation then got URL. I can able to run application with URL.

Now..

I would like to run this application locally before deploying in AWS through Cloud Formation and like to do some changes in source code.

Please help me. 

Thanks and Regards
Ram

**Comment by matteofigus** [comment]
Hi, have you seen the guidelines here? https://github.com/aws-samples/amazon-rekognition-ppe/tree/master/demo#making-changes-to-the-code-and-customization

**Comment by RamGitHub83** [comment]
Hi Matteofigus,

Yes, I go through but not clear to me. I am new to python.
Please help me how can I run this application locally.
which .py file need to run and Is it required new config file to run this locally.

Thanks
Ram

**Comment by matteofigus** [comment]
The demo you deployed has no python. Have you managed to run the frontend locally? That allows to make modifications to the application which is in Javascript and React. 

If you need to make changes to the lambdas, which are again in JavaScript, the code is inside `demo/src/functions/detect`. After you make changes to that, you need to repackage the CloudFormation and redeploy it.

The folders containing python scripts are other examples.

**Comment by RamGitHub83** [comment]
Hi Matteofigus,
Demo application mapped with Web camera, which is running fine.
We want to run the application with CC Cameras , please help me in that.
My understanding is we need to change values in config.json under frame-extraction folder.
[
  {
    "area": "example-area",
    "subarea": "example-sub-area",
    "videoStreamUrl": "192.168.86.50",
    "s3Bucket": "example-bucket-name",
    "isFisheye": false,
    "frameCaptureThreshold": 300
  }
]

Is it correct place? if not please share file name , where need to change.

Please share same values of CC camera details to integrate with this application.

Thanks
Ram

**Comment by matteofigus** [comment]
The content in the `frame-extraction` is just a sample for reading a stream and storing the frames into a s3 bucket, but it's not connected to the demo you deployed.

If you want to use that script, you can run it somewhere, for instance inside a container or an instance, and after saving to an S3 bucket you could implement a S3 event notification to trigger a lambda that could call Rekognition, or similar.

**Comment by RamGitHub83** [comment]
Could you please elaborate on below points.

1. Step by step process how to integrate CC Camera to this application.
2. how can I run this application locally after setting CC camera details by using frontend code.(path of these files)

Thanks in advance

Regards
Ram

**Comment by matteofigus** [comment]
Hi Ram, there is a section of the Rekognition docs that dives into various approaches to work with stored videos:
https://docs.aws.amazon.com/rekognition/latest/dg/video.html

As said before, the demo is for webcam. Is not for stored videos. If you want to work with stored videos, you will probably need to process the stored video, save the result in a database, and then create a frontend that queries the database to see the results.

**Comment by RamGitHub83** [comment]
Hi Matteofigus ,

As you said 

" The demo you deployed has **no python**. Have you managed to run the frontend locally? That allows to make modifications to the application which is in Javascript and React."

As I said I am new to python, 

Please help me in below points.
1. How/where can I get frontend code (python scripts, Javascript and React) for this application. I will look into frontend code.
2. How can I repackage the CloudFormation and redeploy it (after some modifications)

Thanks
Ram

**Comment by RamGitHub83** [comment]
Hi Matteofigus ,

I am waiting for your response for frontend code of this PPE application.

Thanks
Ram

**Comment by ctd** [comment]
1. All of the code used in the demo is inside this git repository, under `demo/src/`.
2. Please see the documentation for the aws-cli `cloudformation package` command at: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/package.html

**Comment by RamGitHub83** [comment]
Hi ctd,
Thanks for response.
Please help me, in which file I need to replace CC camera details with web camera details.
As currently this application getting feed from web camera, we need to test this application with CC camera. 

Thanks in advance   

Regards
Ram

**Comment by ctd** [comment]
Sorry, but it's not as simple as just changing some details in a file. 

This demo was developed to use your web browser's ability to capture from a webcam -- if you're able to have your CC camera appear as a webcam to the browser then you may be able to make it work.

Otherwise, it will depend on the specific CC camera you're using and how you're able to capture frames from it. You may be able to reuse some code from this demo, but that's not certain.

If you need help building a solution specific to your requirements then I'd encourage you to reach out to an [AWS Partner](https://partners.amazonaws.com/) who can help you to build something bespoke.

Please let me know if there's anything we can help you with in using this demo.
